### ISSUE TITLE
Tick count callback is broken

### ISSUE THREAD

**Issue by aendrew** [times/axisJS#60]
![image](https://cloud.githubusercontent.com/assets/185041/5876981/b9fd12a8-a313-11e4-96e0-938285c97bae.png)

**Comment by aendrew** [comment]
Issue is with jQuery.minicolors. Changing issue title to reflect.

**Comment by aendrew** [comment]
It's a C3 issue. If tick count is specified for a categorical axis, "undefined" is returned. It *kind* of worked in 0.3.0, though?

**Comment by aendrew** [comment]
Logged at masayuki0812/c3#935.

**Comment by aendrew** [comment]
Kicking into the tall grasses because it's a C3 issue resolved in its next release.

**Comment by rexmondo** [comment]
The tall grasses are where the wild pokemon are though

**Comment by aendrew** [comment]
![http://i1.kym-cdn.com/photos/images/newsfeed/000/065/215/129012076232534752.jpg]
